apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  cluster:
    name: cluster-example

  method: plugin
  pluginConfiguration:
    name: objstore-backup.dougkirkley
